# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798a360b069520b97c4863891ebd5335cc91654355b01f4254c764e3a4bd663080fe03a0db98059aa77f5d9a8bf72ee9e8cb234117508857e5fa7f0382591b4a

test:
  secret_key_base: 9925ab8cf17f1d49fd9038ca593505cbf3cf9436368860ffd6b12e57a532d5d81479033a6dd03b6b9c96dc44e47586c85bf1ace05aac5d1d37f4533f30235342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
